version: '2'

services:
  jmeter:
    build: ./jmeter/
    ports:
      - "1099:1099"
    volumes:
      - data:/data/
    tty: false
    networks:
      - prodnetwork
    container_name: liquibase_jmeter

volumes:
  data: {}
  
networks:
  prodnetwork:
    driver: bridge
