version: '2'

services:
  jmeter:
    build: ./jmeter/
    ports:
      - "1099:1099"
    volumes:
      - data:/data/
    tty: true
    networks:
      - prodnetwork

volumes:
  data: {}
  
networks:
  prodnetwork:
    driver: bridge
